//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suklemin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analizators_
    {
        /// <summary>
        /// Использование анализатора в работе анализатора
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Analizators_()
        {
            this.Work_analizators_ = new HashSet<Work_analizators_>();
        }
        /// <summary>
        /// ID анализатора
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// Наименование анализатора
        /// </summary>
        public string name { get; set; }
        /// <summary>
        /// Виртуальный объект класса работы анализатора
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work_analizators_> Work_analizators_ { get; set; }
    }
}
