//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suklemin
{
    using System;
    using System.Collections.Generic;
    using Path = System.IO.Path;
    /// <summary>
    /// Класс истории услуг в заказах
    /// </summary>
    public partial class HistoryResearch_
    {
        /// <summary>
        /// Использование истории в истории работы анализаторов
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HistoryResearch_()
        {
            this.Work_analizators_ = new HashSet<Work_analizators_>();
        }
        /// <summary>
        /// Идентификационный номер истории исследования
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// Код заказа
        /// </summary>
        public Nullable<int> orderId { get; set; }
        /// <summary>
        /// Код услуги
        /// </summary>
        public Nullable<int> services { get; set; }
        /// <summary>
        /// Код анализатора текущей услуги
        /// </summary>
        public int analisator { get; set; }
        /// <summary>
        /// Виртуальный объект сервиса
        /// </summary>
        public virtual Services_ Services_ { get; set; }
        /// <summary>
        /// Виртуальный объект заказа
        /// </summary>
        public virtual Order_ Order_ { get; set; }
        /// <summary>
        /// Виртуальный объект истории работы анализатора
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work_analizators_> Work_analizators_ { get; set; }
    }
}
