//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suklemin
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Класс для истории входов/выходов
    /// </summary>
    public partial class HistoryEnter_
    {
        /// <summary>
        /// идентификационный номер истории входов
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// идентификационный номер пользователя
        /// </summary>
        public Nullable<int> userId { get; set; }
        /// <summary>
        /// ip адрес пользователя
        /// </summary>
        public string ip { get; set; }
        /// <summary>
        /// Дата входа
        /// </summary>
        public Nullable<System.DateTime> date { get; set; }
        /// <summary>
        /// Идентификационный номер ошибки
        /// </summary>
        public Nullable<int> erorId { get; set; }
        /// <summary>
        /// Виртуальный объект ошибки
        /// </summary>
        public virtual Eror_ Eror_ { get; set; }
        /// <summary>
        /// Виртуальный объект пользователя
        /// </summary>
        public virtual Users_ Users_ { get; set; }
        /// <summary>
        /// Использование виртуального пользователя для вывода логинов
        /// </summary>
        public string userlogin
        {
            get
            {
                return Users_.login;
            }
            set { }
        }
        /// <summary>
        /// Использование виртуальной ошибки для вывода
        /// </summary>
        public string errorName
        {
            get
            {
                if(Eror_ == null)
                {
                    return "Вход";
                }
                else
                {
                    return Eror_.erorName;
                }
            }
            set { }
        }
    }
}
