//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suklemin
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Компания
    /// </summary>
    public partial class InsuranceCompany_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsuranceCompany_()
        {
            this.Users_ = new HashSet<Users_>();
        }
    
        public int id { get; set; }
        public string insuranceCompany { get; set; }
        public string adress { get; set; }
        public Nullable<int> INN { get; set; }
        public string RC { get; set; }
        public string BIK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_> Users_ { get; set; }
    }
}
