//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suklemin
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Класс заказа
    /// </summary>
    public partial class Order_
    {
        /// <summary>
        /// Класс заказов
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        
        public Order_()
        {
            this.HistoryResearch_ = new HashSet<HistoryResearch_>();
        }
        /// <summary>
        /// Идентификационный номер заказа
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// Дата заказа
        /// </summary>
        public Nullable<System.DateTime> date { get; set; }
        /// <summary>
        /// Пользователь запросивший заказ
        /// </summary>
        public Nullable<int> userId { get; set; }
        /// <summary>
        /// Статус заказа
        /// </summary>
        public Nullable<int> statusOrder { get; set; }
        /// <summary>
        /// Виртуальный объект истории исследования
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryResearch_> HistoryResearch_ { get; set; }
        /// <summary>
        /// виртуальный объект Статус заказа
        /// </summary>
        public virtual StatusOrder_ StatusOrder_ { get; set; }
        /// <summary>
        /// Виртуальный объект пользователя
        /// </summary>
        public virtual Users_ Users_ { get; set; }  
        /// <summary>
        /// Вывод данных пользователя
        /// </summary>
        public string UserID
        {
            get
            {
                if(Users_ == null)
                {
                    return "Пользователь потерен в лесу";
                }
                else
                {
                    return $"{Users_.secondName} {Users_.firstName} {Users_.thirdName}";
                }
            }
        }
        /// <summary>
        /// Вывод данных статуса
        /// </summary>
        public string StatusOrderIn
        {
            get
            {
                if(StatusOrder_ == null)
                {
                    return "Статус заказа потерян";
                }
                else
                {
                    return StatusOrder_.name;
                }
            }
        }
    }
}
