//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suklemin
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Тип полиса
    /// </summary>
    public partial class Type_
    {
        /// <summary>
        /// Тип полиса у пользователя
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Type_()
        {
            this.Users_ = new HashSet<Users_>();
        }
        /// <summary>
        /// Идентификационный номер типа полиса
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// Наименование типа полиса
        /// </summary>
        public string name { get; set; }
        /// <summary>
        /// Виртуальный объект пользователя полиса 
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_> Users_ { get; set; }
    }
}
