//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suklemin
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Класс пользователей
    /// </summary>
    public partial class Users_
    {
        /// <summary>
        /// Классы в которых используется пользователь
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users_()
        {
            this.HistoryEnter_ = new HashSet<HistoryEnter_>();
            this.Order_ = new HashSet<Order_>();
            this.Work_analizators_ = new HashSet<Work_analizators_>();
            this.Work_Box_ = new HashSet<Work_Box_>();
        }
        /// <summary>
        /// Идентификационный номер пользователя
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// Имя
        /// </summary>
        public string firstName { get; set; }
        /// <summary>
        /// Фамилия
        /// </summary>
        public string secondName { get; set; }
        /// <summary>
        /// Отчество
        /// </summary>
        public string thirdName { get; set; }
        /// <summary>
        /// Логин
        /// </summary>
        public string login { get; set; }
        /// <summary>
        /// Пароль
        /// </summary>
        public string password { get; set; }
        /// <summary>
        /// Тип полиса
        /// </summary>
        public Nullable<int> type { get; set; }
        /// <summary>
        /// Дата рождения
        /// </summary>
        public Nullable<System.DateTime> birthDate { get; set; }
        /// <summary>
        /// Паспорт
        /// </summary>
        public string passport { get; set; }
        /// <summary>
        /// Номер телефона
        /// </summary>
        public string phoneNumber { get; set; }
        /// <summary>
        /// Электронная почта
        /// </summary>
        public string E_mail { get; set; }
        /// <summary>
        /// Номер страховки
        /// </summary>
        public Nullable<double> insuranceNumber { get; set; }
        /// <summary>
        /// Код страховой компании
        /// </summary>
        public Nullable<int> insuranceCompany { get; set; }
        /// <summary>
        /// Код роли
        /// </summary>
        public Nullable<int> role { get; set; }
        /// <summary>
        /// Полное имя для вывода фио
        /// </summary>
        public string FullName
        {
            get
            {
                return $"{secondName} {firstName} {thirdName} {phoneNumber}";
            }
        }
        /// <summary>
        /// Вывод полного имени при отображении объекта
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return FullName;
        }
        /// <summary>
        /// Виртуальный объект истории входов
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryEnter_> HistoryEnter_ { get; set; }
        /// <summary>
        /// Виртуальный объект страховой компании
        /// </summary>
        public virtual InsuranceCompany_ InsuranceCompany_ { get; set; }
        /// <summary>
        /// Виртуальный объект заказов
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_> Order_ { get; set; }
        /// <summary>
        /// Виртуальный объект роли
        /// </summary>
        public virtual Role_ Role_ { get; set; }
        /// <summary>
        /// Виртуальный объект типа полиса
        /// </summary>
        public virtual Type_ Type_ { get; set; }
        /// <summary>
        /// Виртуальный объект работы аналихатора
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work_analizators_> Work_analizators_ { get; set; }
        /// <summary>
        /// Работа коробок нереализованная из-за конца работы
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work_Box_> Work_Box_ { get; set; }
    }
}
