//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suklemin
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Неиспользуемый класс
    /// </summary>
    public partial class Work_Box_
    {

        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> companyId { get; set; }
        public Nullable<decimal> sum { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Users_ Users_ { get; set; }
    }
}
