//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suklemin
{
    using System;
    using System.Collections.Generic;
   
    /// <summary>
    /// Класс работы анализаторов отоюражает историю работы анализаторов
    /// </summary>
    public partial class Work_analizators_
    {
        /// <summary>
        /// Идентификационный номер работы анализатора
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// код оказываемой Услуги в заказе
        /// </summary>
        public Nullable<int> historyResearchId { get; set; }
        /// <summary>
        /// Код анализатора
        /// </summary>
        public Nullable<int> analisatorId { get; set; }
        /// <summary>
        /// Дата
        /// </summary>
        public Nullable<System.DateTime> date { get; set; }
        /// <summary>
        /// Затраченное время
        /// </summary>
        public Nullable<int> time { get; set; }
        /// <summary>
        /// Код пользователя работающего за анализатором
        /// </summary>
        public Nullable<int> employeeId { get; set; }
        /// <summary>
        /// Результат
        /// </summary>
        public string result { get; set; }
        /// <summary>
        /// Виртуальный объект анализатора
        /// </summary>
        public virtual Analizators_ Analizators_ { get; set; }
        /// <summary>
        /// Виртуальный объект услуги в заказе
        /// </summary>
        public virtual HistoryResearch_ HistoryResearch_ { get; set; }
        /// <summary>
        /// Виртуальный объект пользователя
        /// </summary>
        public virtual Users_ Users_ { get; set; }
    }
}
